import {
  getDb,
  quotes,
  quoteLineItems,
  quoteActivities,
  jobs,
  jobLineItems,
  jobActivities,
  eq,
  and,
  asc,
  sql,
} from "@hvac-saas/database";
import { attachChecklistToJob } from "./job-helpers.js";
import {
  getDefaultPipelineId,
  getFirstStage,
  resolveStage,
} from "../services/job-stages.service.js";

interface QuoteData {
  id: string;
  tenantId: string;
  customerId: string;
  quoteNumber: string | null;
  subtotal: string;
  taxRate: string | null;
  discountAmount: string | null;
  equipmentId: string | null;
  status: string;
  customerScheduledDate?: string | null;
  customerScheduledTime?: string | null;
}

type ServiceType = (typeof jobs.serviceType)["_"]["data"];

interface ConvertOptions {
  pipelineStageId?: string;
  scheduledDate?: string;
  scheduledTime?: string;
  // The pgEnum union, not `string` — this used to be laundered through
  // `as never` at the insert, which meant any caller-supplied value reached a
  // Postgres enum unchecked and failed as a 500 rather than a 400.
  serviceType?: ServiceType;
  performedBy?: string | null;
}

/**
 * Convert a quote to a job. Shared between:
 * - Internal POST /quotes/:id/convert (authenticated)
 * - Public POST /public/quote/:token/accept (when auto-convert is enabled)
 *
 * Returns the created job's id and jobNumber.
 * Wrapped in a transaction with SELECT FOR UPDATE to prevent duplicate conversion.
 */
export async function convertQuoteToJob(
  db: ReturnType<typeof getDb>,
  quote: QuoteData,
  options: ConvertOptions,
): Promise<{ jobId: string; jobNumber: string }> {
  const { tenantId } = quote;

  return db.transaction(async (tx) => {
    // Lock the quote row to prevent concurrent conversions
    const [lockedQuote] = await tx
      .select({ id: quotes.id, convertedToJobId: quotes.convertedToJobId })
      .from(quotes)
      .where(and(eq(quotes.id, quote.id), eq(quotes.tenantId, tenantId)))
      .for("update");

    if (!lockedQuote) {
      throw new Error("Quote not found");
    }
    if (lockedQuote.convertedToJobId) {
      throw new Error("ALREADY_CONVERTED");
    }

    // Resolve the stage through the one service allowed to decide what column a
    // job sits in (QUO-02). This used to write `jobs.status` by hand from a bare
    // stage name and never set `stage_id` at all, so a job created from a quote
    // was outside the model the rest of Jobs reasons about: it counted as 0 in
    // the stage-keyed pipeline counts, matched no `?lifecycle=` filter, and was
    // stranded on the board the moment its stage was deleted.
    const pipelineId = await getDefaultPipelineId(tx, tenantId);

    // `resolveStage` is tenant-scoped and rejects a stage belonging to a
    // different pipeline than the job (QUO-27) — passing one used to produce a
    // job in pipeline A whose status named a column only pipeline B has.
    const stage = options.pipelineStageId
      ? await resolveStage(tx, {
          tenantId,
          pipelineId,
          stageId: options.pipelineStageId,
        })
      : pipelineId
        ? await getFirstStage(tx, { tenantId, pipelineId })
        : null;

    if (options.pipelineStageId && !stage) {
      throw new Error("INVALID_STAGE");
    }

    // Determine scheduled date — prefer customer-chosen date from portal
    const scheduledDate =
      options.scheduledDate ??
      quote.customerScheduledDate ??
      new Date().toISOString().split("T")[0];

    // Determine scheduled time — prefer customer-chosen time from portal
    const scheduledTime =
      options.scheduledTime ?? quote.customerScheduledTime ?? null;

    // Determine service type — use provided option or fall back to "repair"
    const serviceType = options.serviceType ?? "repair";

    // Create job
    const [job] = await tx
      .insert(jobs)
      .values({
        tenantId,
        customerId: quote.customerId,
        pipelineId,
        stageId: stage?.id ?? null,
        jobNumber: "", // Auto-generated by DB trigger
        title: `Job from ${quote.quoteNumber}`,
        // Mirrors the resolved stage's name, exactly as `POST /jobs` does. The
        // literal fallback only applies to a tenant with no pipeline at all.
        status: stage?.name ?? "scheduled",
        scheduledDate,
        scheduledStart: scheduledTime,
        taxRate: quote.taxRate ?? "0",
        serviceType,
        equipmentId: quote.equipmentId ?? null,
      })
      .returning();

    // Copy quote line items to job line items
    const quoteItems = await tx
      .select()
      .from(quoteLineItems)
      .where(
        and(
          eq(quoteLineItems.tenantId, tenantId),
          eq(quoteLineItems.quoteId, quote.id),
        ),
      )
      .orderBy(asc(quoteLineItems.sortOrder));

    if (quoteItems.length > 0) {
      await tx.insert(jobLineItems).values(
        quoteItems.map((item) => ({
          tenantId,
          jobId: job.id,
          catalogItemId: item.catalogItemId,
          itemType: item.itemType,
          description: item.description,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          sortOrder: item.sortOrder ?? 0,
        })),
      );
    }

    // Recalculate job totals (include discount from quote)
    const subtotal = parseFloat(quote.subtotal);
    const taxRate = parseFloat(quote.taxRate ?? "0");
    const discountAmount = parseFloat(quote.discountAmount ?? "0");
    const taxAmount = subtotal * taxRate;
    const totalAmount = subtotal + taxAmount - discountAmount;

    await tx
      .update(jobs)
      .set({
        subtotal: subtotal.toFixed(2),
        taxAmount: taxAmount.toFixed(2),
        totalAmount: totalAmount.toFixed(2),
        updatedAt: new Date(),
      })
      .where(and(eq(jobs.id, job.id), eq(jobs.tenantId, tenantId)));

    // Auto-attach checklist
    await attachChecklistToJob(
      tx,
      job.id,
      tenantId,
      options.serviceType ?? "repair",
      options.performedBy ?? "system",
    );

    // Update quote with converted job reference
    await tx
      .update(quotes)
      .set({
        convertedToJobId: job.id,
        status:
          quote.status !== "accepted" ? "accepted" : quote.status,
        updatedAt: new Date(),
      })
      .where(and(eq(quotes.id, quote.id), eq(quotes.tenantId, tenantId)));

    // Re-fetch the job to get the auto-generated jobNumber
    const [createdJob] = await tx
      .select()
      .from(jobs)
      .where(and(eq(jobs.id, job.id), eq(jobs.tenantId, tenantId)));

    // Log activity on the quote
    await tx.insert(quoteActivities).values({
      tenantId,
      quoteId: quote.id,
      type: "quote.converted",
      description: `Converted to job ${createdJob.jobNumber}`,
      performedBy: options.performedBy ?? null,
      metadata: { jobId: job.id },
    });

    // Log activity on the newly created job
    await tx.insert(jobActivities).values({
      tenantId,
      jobId: job.id,
      type: "job.created",
      description: `Created from quote ${quote.quoteNumber}`,
      performedBy: options.performedBy ?? null,
      metadata: { quoteId: quote.id },
    });

    return { jobId: job.id, jobNumber: createdJob.jobNumber };
  });
}
