import {
  getDb,
  quotes,
  quoteLineItems,
  quoteActivities,
  jobs,
  jobLineItems,
  eq,
  and,
  asc,
} from "@hvac-saas/database";
import { attachChecklistToJob } from "./job-helpers.js";

interface QuoteData {
  id: string;
  tenantId: string;
  customerId: string;
  quoteNumber: string | null;
  subtotal: string;
  taxRate: string | null;
  discountAmount: string | null;
  equipmentId: string | null;
  status: string;
}

interface ConvertOptions {
  pipelineStageId?: string;
  scheduledDate?: string;
  scheduledTime?: string;
  performedBy?: string | null;
}

/**
 * Convert a quote to a job. Shared between:
 * - Internal POST /quotes/:id/convert (authenticated)
 * - Public POST /public/quote/:token/accept (when auto-convert is enabled)
 *
 * Returns the created job's id and jobNumber.
 */
export async function convertQuoteToJob(
  db: ReturnType<typeof getDb>,
  quote: QuoteData,
  options: ConvertOptions,
): Promise<{ jobId: string; jobNumber: string }> {
  const { tenantId } = quote;

  // Resolve default pipeline
  const { jobPipelineStages, pipelines: pipelinesTable } = await import(
    "@hvac-saas/database"
  );
  const defaultPipeline = await db
    .select({ id: pipelinesTable.id })
    .from(pipelinesTable)
    .where(
      and(
        eq(pipelinesTable.tenantId, tenantId),
        eq(pipelinesTable.isDefault, true),
      ),
    )
    .then((r) => r[0]);
  const pipelineId = defaultPipeline?.id ?? null;

  // Resolve pipeline stage (user-selected or first default)
  let jobStatus = "Scheduled";
  if (options.pipelineStageId) {
    const selectedStage = await db
      .select({ name: jobPipelineStages.name })
      .from(jobPipelineStages)
      .where(
        and(
          eq(jobPipelineStages.id, options.pipelineStageId),
          eq(jobPipelineStages.tenantId, tenantId),
        ),
      )
      .then((r) => r[0]);
    if (selectedStage) jobStatus = selectedStage.name;
  } else if (pipelineId) {
    const firstStage = await db
      .select({ name: jobPipelineStages.name })
      .from(jobPipelineStages)
      .where(eq(jobPipelineStages.pipelineId, pipelineId))
      .orderBy(asc(jobPipelineStages.sortOrder))
      .limit(1)
      .then((r) => r[0]);
    if (firstStage) jobStatus = firstStage.name;
  }

  // Determine scheduled date
  const scheduledDate =
    options.scheduledDate ?? new Date().toISOString().split("T")[0];

  // Create job
  const [job] = await db
    .insert(jobs)
    .values({
      tenantId,
      customerId: quote.customerId,
      pipelineId,
      jobNumber: "", // Auto-generated by DB trigger
      title: `Job from ${quote.quoteNumber}`,
      status: jobStatus,
      scheduledDate,
      scheduledStart: options.scheduledTime ?? null,
      taxRate: quote.taxRate ?? "0",
      serviceType: "repair" as never,
      equipmentId: quote.equipmentId ?? null,
    })
    .returning();

  // Copy quote line items to job line items
  const quoteItems = await db
    .select()
    .from(quoteLineItems)
    .where(
      and(
        eq(quoteLineItems.tenantId, tenantId),
        eq(quoteLineItems.quoteId, quote.id),
      ),
    )
    .orderBy(asc(quoteLineItems.sortOrder));

  if (quoteItems.length > 0) {
    await db.insert(jobLineItems).values(
      quoteItems.map((item) => ({
        tenantId,
        jobId: job.id,
        catalogItemId: item.catalogItemId,
        itemType: item.itemType,
        description: item.description,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        sortOrder: item.sortOrder ?? 0,
      })),
    );
  }

  // Recalculate job totals (include discount from quote)
  const subtotal = parseFloat(quote.subtotal);
  const taxRate = parseFloat(quote.taxRate ?? "0");
  const discountAmount = parseFloat(quote.discountAmount ?? "0");
  const taxAmount = subtotal * taxRate;
  const totalAmount = subtotal + taxAmount - discountAmount;

  await db
    .update(jobs)
    .set({
      subtotal: subtotal.toFixed(2),
      taxAmount: taxAmount.toFixed(2),
      totalAmount: totalAmount.toFixed(2),
      updatedAt: new Date(),
    })
    .where(and(eq(jobs.id, job.id), eq(jobs.tenantId, tenantId)));

  // Auto-attach checklist
  await attachChecklistToJob(
    db,
    job.id,
    tenantId,
    "repair",
    options.performedBy ?? "system",
  );

  // Update quote with converted job reference
  await db
    .update(quotes)
    .set({
      convertedToJobId: job.id,
      status:
        quote.status !== "accepted" ? ("accepted" as never) : quote.status,
      updatedAt: new Date(),
    })
    .where(and(eq(quotes.id, quote.id), eq(quotes.tenantId, tenantId)));

  // Re-fetch the job to get the auto-generated jobNumber
  const [createdJob] = await db.select().from(jobs).where(eq(jobs.id, job.id));

  // Log activity
  await db.insert(quoteActivities).values({
    tenantId,
    quoteId: quote.id,
    type: "quote.converted",
    description: `Converted to job ${createdJob.jobNumber}`,
    performedBy: options.performedBy ?? null,
    metadata: { jobId: job.id },
  });

  return { jobId: job.id, jobNumber: createdJob.jobNumber };
}
