-- =============================================================================
-- RLS Policies, updated_at trigger, and auto-numbering triggers
-- This migration is hand-written (not generated by Drizzle) because
-- Drizzle does not support RLS policies or database triggers.
-- All SQL is idempotent — safe to re-run.
-- =============================================================================

-- =============================================================================
-- 1. updated_at trigger function
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to all tables that have an updated_at column
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'tenants', 'users', 'tenant_subscriptions', 'customers',
      'equipment', 'maintenance_contracts', 'bookings',
      'jobs', 'invoices', 'quotes'
    ])
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_trigger WHERE tgname = 'trg_' || tbl || '_updated_at'
    ) THEN
      EXECUTE format(
        'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
        tbl, tbl
      );
    END IF;
  END LOOP;
END $$;

-- =============================================================================
-- 2. Auto-numbering trigger functions
-- =============================================================================

-- Job number: JOB-YYYY-XXXX
CREATE OR REPLACE FUNCTION generate_job_number()
RETURNS TRIGGER AS $$
DECLARE
  current_year TEXT;
  next_seq INT;
BEGIN
  IF NEW.job_number IS NULL OR NEW.job_number = '' THEN
    current_year := EXTRACT(YEAR FROM NOW())::TEXT;
    SELECT COALESCE(
      MAX(CAST(SUBSTRING(job_number FROM 'JOB-\d{4}-(\d+)') AS INT)), 0
    ) + 1
    INTO next_seq
    FROM jobs
    WHERE tenant_id = NEW.tenant_id
      AND job_number LIKE 'JOB-' || current_year || '-%';
    NEW.job_number := 'JOB-' || current_year || '-' || LPAD(next_seq::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_jobs_auto_number') THEN
    CREATE TRIGGER trg_jobs_auto_number
      BEFORE INSERT ON jobs
      FOR EACH ROW
      EXECUTE FUNCTION generate_job_number();
  END IF;
END $$;

-- Invoice number: INV-YYYY-XXXX
CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER AS $$
DECLARE
  current_year TEXT;
  next_seq INT;
BEGIN
  IF NEW.invoice_number IS NULL OR NEW.invoice_number = '' THEN
    current_year := EXTRACT(YEAR FROM NOW())::TEXT;
    SELECT COALESCE(
      MAX(CAST(SUBSTRING(invoice_number FROM 'INV-\d{4}-(\d+)') AS INT)), 0
    ) + 1
    INTO next_seq
    FROM invoices
    WHERE tenant_id = NEW.tenant_id
      AND invoice_number LIKE 'INV-' || current_year || '-%';
    NEW.invoice_number := 'INV-' || current_year || '-' || LPAD(next_seq::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_invoices_auto_number') THEN
    CREATE TRIGGER trg_invoices_auto_number
      BEFORE INSERT ON invoices
      FOR EACH ROW
      EXECUTE FUNCTION generate_invoice_number();
  END IF;
END $$;

-- Quote number: QT-YYYY-XXXX
CREATE OR REPLACE FUNCTION generate_quote_number()
RETURNS TRIGGER AS $$
DECLARE
  current_year TEXT;
  next_seq INT;
BEGIN
  IF NEW.quote_number IS NULL OR NEW.quote_number = '' THEN
    current_year := EXTRACT(YEAR FROM NOW())::TEXT;
    SELECT COALESCE(
      MAX(CAST(SUBSTRING(quote_number FROM 'QT-\d{4}-(\d+)') AS INT)), 0
    ) + 1
    INTO next_seq
    FROM quotes
    WHERE tenant_id = NEW.tenant_id
      AND quote_number LIKE 'QT-' || current_year || '-%';
    NEW.quote_number := 'QT-' || current_year || '-' || LPAD(next_seq::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_quotes_auto_number') THEN
    CREATE TRIGGER trg_quotes_auto_number
      BEFORE INSERT ON quotes
      FOR EACH ROW
      EXECUTE FUNCTION generate_quote_number();
  END IF;
END $$;

-- =============================================================================
-- 3. Row Level Security — Enable on tenant-scoped tables
-- =============================================================================

-- Enable RLS on all tenant tables (idempotent — no error if already enabled)
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_checklist_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE refrigerant_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_events ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- 4. RLS Policies — Tenant isolation via JWT tenant_id claim
-- =============================================================================

-- Helper: extract tenant_id from Supabase JWT
-- Usage: auth.jwt() ->> 'tenant_id'

-- Macro for tenant isolation policies (SELECT, INSERT, UPDATE, DELETE)
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'users', 'tenant_subscriptions', 'customers', 'catalog_items',
      'equipment', 'maintenance_contracts', 'bookings',
      'jobs', 'job_line_items', 'job_photos', 'job_checklist_completions',
      'invoices', 'invoice_line_items', 'invoice_payments',
      'quotes', 'quote_line_items', 'refrigerant_logs',
      'availability_schedules', 'schedule_overrides',
      'checklist_templates', 'checklist_items'
    ])
  LOOP
    -- SELECT policy
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = tbl || '_tenant_select'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR SELECT USING (tenant_id = (auth.jwt() ->> ''tenant_id'')::uuid)',
        tbl || '_tenant_select', tbl
      );
    END IF;

    -- INSERT policy
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = tbl || '_tenant_insert'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR INSERT WITH CHECK (tenant_id = (auth.jwt() ->> ''tenant_id'')::uuid)',
        tbl || '_tenant_insert', tbl
      );
    END IF;

    -- UPDATE policy
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = tbl || '_tenant_update'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR UPDATE USING (tenant_id = (auth.jwt() ->> ''tenant_id'')::uuid)',
        tbl || '_tenant_update', tbl
      );
    END IF;

    -- DELETE policy
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = tbl || '_tenant_delete'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR DELETE USING (tenant_id = (auth.jwt() ->> ''tenant_id'')::uuid)',
        tbl || '_tenant_delete', tbl
      );
    END IF;
  END LOOP;
END $$;

-- Tenants table: tenant can only see their own row
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'tenants' AND policyname = 'tenants_tenant_select'
  ) THEN
    CREATE POLICY tenants_tenant_select ON tenants
      FOR SELECT USING (id = (auth.jwt() ->> 'tenant_id')::uuid);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'tenants' AND policyname = 'tenants_tenant_update'
  ) THEN
    CREATE POLICY tenants_tenant_update ON tenants
      FOR UPDATE USING (id = (auth.jwt() ->> 'tenant_id')::uuid);
  END IF;
END $$;

-- Platform events: INSERT-only for tenants (no SELECT — admin reads via service role)
-- The loop above doesn't include platform_events, so we handle it separately
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'platform_events' AND policyname = 'platform_events_tenant_insert'
  ) THEN
    CREATE POLICY platform_events_tenant_insert ON platform_events
      FOR INSERT WITH CHECK (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);
  END IF;
END $$;

-- =============================================================================
-- 5. Admin tables — RLS DISABLED (accessed via service role only)
-- =============================================================================
-- admin_users, admin_audit_log, admin_impersonation_sessions
-- These tables do NOT have RLS enabled. They are only accessed via the
-- Supabase service role key from Fastify admin routes.
-- Drizzle-generated migration creates them without RLS by default.
